name: Continuous Integration

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    # Setup environment
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: true
        lfs: true
    - uses: actions/setup-java@v2
      name: Setup Java 11
      with:
        distribution: temurin
        java-version: 11
    - uses: subosito/flutter-action@v1
      name: Setup Flutter
      with:
        channel: stable
    - run: flutter pub get
      name: Install packages
    - run: echo $GOOGLE_SERVICES > ./android/app/google-services.json
      name: Add google-services.json
      env:
       GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}

    # Test the code
    - run: flutter analyze .
      name: Analyze the code
    - run: flutter test
      name: Run test
